# NumPy: Funções Universais (UFuncs)
Neste tópico, propomos o estudo do pacote `NumPy`, cujo objetivo é fornecer suporte para arrays multidimensionais, que possuem implementações prontas para operações básicas e funções de algebra linear extremamente úteis. Este pacote é a base de grande parte dos pacotes do Python que serão futuramente estudados. A implementação deste pacote é feita através de C, logo, ele é extremamente otimizado (devido a tipagém estática e uso de memória contigua), sendo ótimo para carregar, armazenear, e manipular dados dentro de memória no Python.

## Funções Universais
Até então, analisamos a estrutura básica do NumPy, como definir arrays utilizando ele e o funcionamento básico. A principal aplicação do NumPy é devido ao seu ótimo desempenho para computar cálculos. Entretanto, para atingir este alto desempenho, é necessário utilizar operações vetorizadas, que normalmente são implementadas através das funções universais do NumPy (módulo `ufuncs`).

A lerdeza do Python normalmente se destaca ao fazer pequenas operações de forma repetida, como por exemplo em laços de iteração, que é principalmente causada pela checagem de tipos que é necessário que o CPython faça para cada ciclo do laço. 

Como o NumPy possuí arrays de tipo fixo, funções compiladas que se aproveitam desta vantagem podem otimizar essas operações. Essas funções são chamadas de operações vetorizadas, e permitem indicar uma operação, e o NumPy cuida de aplicar a operação sobre cada elemento. 

## Tipos de UFuncs
Há dois tipos principais de funções universais: Unárias e Binárias. Funções universais unárias operam sobre uma única entrada (array), enquanto as binárias operam sobre duas entradas.
> Dica: Para uma lista de UFuncs completa, favor acessar o [link](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs). Lá há mais informações sobre UFuncs para operações matemáticas; funções trigonômétricas; Operações de Bits; Funções de Comparações e Funções para Floats. Outra dica é a utilização do submódulo `special` ([link](https://docs.scipy.org/doc/scipy/reference/special.html)) dentro do módulo `scipy`, onde há inumeras funções matemáticas que o NumPy não implementa. 

## Aritmética de Arrays
As operações aritméticas simples são extendidas para arrays, e permitem por exemplo adicionar, subtrair, dividir e multiplicar um valor inteiro em todos elementos do array com uma única linha.

In [23]:
import numpy as np
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

A adição, multiplicação, subtração, divisão, divisão inteira, potênciação e resto de divisão pode ser feita da mesma forma que os valores padrões do Python, e o valor opera sobre cada elemento do array. É possível até mesmo encadear essas operações. Todas esses funções são decoradores para funções do NumPy que realizam estas operações. 

In [24]:
x + 5

array([5, 6, 7, 8, 9])

In [25]:
x * 2

array([0, 2, 4, 6, 8])

In [26]:
x - 1

array([-1,  0,  1,  2,  3])

In [27]:
x / 5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [28]:
x//2

array([0, 0, 1, 1, 2], dtype=int32)

In [29]:
x ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [30]:
x % 2

array([0, 1, 0, 1, 0], dtype=int32)

## Valores Absolutos
Para obter valores absolutos, é possível utilizar a função `abs()` nativa do Python, entretanto, a função `abs()` do NumPy é uma operação vetorizada, logo é mais otimizada.

In [31]:
x = np.arange(-10,10,3)
np.abs(x)

array([10,  7,  4,  1,  2,  5,  8])

Esta operação  é muito útil quando se trabalhar com valores imaginários pois retorna a magnitude do numero imaginário.

In [32]:
x = np.array([2-1j, 4-2j, 0+2j, 1+0j])
np.abs(x)

array([2.23606798, 4.47213595, 2.        , 1.        ])

## Funções Trigonômétricas
As funções trigonômétricas implementadas pelo NumPy são extremamente úteis. Para utiliar elas, primeiro definimos um array baseado em valores radeanos utilizando o valor de $\pi$ definido pelo NumPy.

In [33]:
p = np.pi
x = np.array([0, p/2, p, 3*p/2])

Então, podemoos utilizar as funções trigonômétricas implementadas pelo NumPy para calcular funções trigonômétricas.  Note que os valores não são exatos já que há erros introduzidos por utilizar numeros de ponto flutuante.

In [34]:
print("x = ", x)
print("sin(x) = ", np.sin(x))
print("cos(x) = ", np.cos(x))
print("tan(x) = ", np.tan(x))

x =  [0.         1.57079633 3.14159265 4.71238898]
sin(x) =  [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
cos(x) =  [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]
tan(x) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15]


Podemos também utilizar as funções trigonométricas inversas. O resultado é retornado em radianos.

In [35]:
x = np.array([-1, 0, 1])
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1  0  1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


Nós podemos utilizar a função `rad2deg()` para converter os valores dos arrays de radianos para graus.

In [36]:
print("x = ", x)
print("arcsin(x) = ", np.rad2deg(np.arcsin(x)))
print("arccos(x) = ", np.rad2deg(np.arccos(x)))
print("arctan(x) = ", np.rad2deg(np.arctan(x)))

x =  [-1  0  1]
arcsin(x) =  [-90.   0.  90.]
arccos(x) =  [180.  90.   0.]
arctan(x) =  [-45.   0.  45.]


## Exponênciais e Logaritmos 
Exponenciais e logaritmos são outros tipos de funções que surgem nos estudos cíentíficos, e é essencial possuir implementações otimizadas para calcular essa funções para um array.

As funções exponenciais disponíveis são `exp()` e `exp2()`. É possível utilizar a função  `power()` para realizar esta operação também. 

In [37]:
x = np.arange(1,5)
print("x = ", x)
print("e^(x) = ", np.exp(x))
print("2^(x) = ", np.exp2(x))
print("3^(x) = ", np.power(3,x))

x =  [1 2 3 4]
e^(x) =  [ 2.71828183  7.3890561  20.08553692 54.59815003]
2^(x) =  [ 2.  4.  8. 16.]
3^(x) =  [ 3  9 27 81]


As funções `log()`, `log2()` e `log10()` produzem respectivamente o logaritmo neperiano, logaritmo em base 2, logaritmo em base 10.

In [38]:
x = np.arange(1,5)
print("x = ", x)
print("ln(x) = ", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [1 2 3 4]
ln(x) =  [0.         0.69314718 1.09861229 1.38629436]
log2(x) =  [0.        1.        1.5849625 2.       ]
log10(x) =  [0.         0.30103    0.47712125 0.60205999]


## Propriedades Avançandas de UFuncs
Há algumas propriedades que podem melhorar o desempenho das UFuncs ainda mais, ou facilitar a vida do programador. Por exemplo, para calculos grandes, pode ser útil informar através da chamada da função qual váriavel será utilizada para armazenar os resultados, ao invés de realizar a atribuição, como demonstramos abaixo. Esta funcionalidade é aplicável para todas as UFuncs, e ocorre através da passagem do paramêtro `out`.

In [39]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
y

array([ 0., 10., 20., 30., 40.])

Para UFuncs binárias, há algumas operações de agregação que podem ser realizadas. Qualquer UFunc podem ser aplicadas utilizando o método `reduce()` da função. Isto aplica a operação entre os elementos, agregando o resultado de cada iteração. Podemos utilizar isso para calcular um somátório ou produtório por exemplo. 

In [40]:
print(x)
print(np.add.reduce(x))
print(np.multiply.reduce(x))

[0 1 2 3 4]
10
0


Para obter os valores acumulados para cada iteração, ao invés de utilizar o método `reduce()`, deve se utilizar o `accumulate()`.

In [41]:
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[ 0  1  3  6 10]
[0 0 0 0 0]


Qualquer UFunc pode computar a saída de todos os pares de duas entradas diferentes utilizando o métodoo `outer()`. Logo, é possível realizar uma linha, criar uma tabela de multiplicação.

In [43]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])