# NumPy: Agregações
Neste tópico, propomos o estudo do pacote `NumPy`, cujo objetivo é fornecer suporte para arrays multidimensionais, que possuem implementações prontas para operações básicas e funções de algebra linear extremamente úteis. Este pacote é a base de grande parte dos pacotes do Python que serão futuramente estudados. A implementação deste pacote é feita através de C, logo, ele é extremamente otimizado (devido a tipagém estática e uso de memória contigua), sendo ótimo para carregar, armazenear, e manipular dados dentro de memória no Python.

## Agregações
Uma função de agregação permite resumir valores númericos através de algum conjunto de operações, tendo aplicações em estátística descritiva, além de ser aplicada em vários campos como operações matemáticas. O NumPy possuí implementações otimizadas para estes vastos tipos de operações.

### Somatório
Apesar de existir a implementação do Python para realizar somátório de um iterável, a do NumPy é muito mais otimizada, por isso, recomendo se utilizar ela.

In [16]:
import numpy as np
x = np.arange(10)
print(x)
print(np.sum(x)) # Implementacao do NumPy
print(sum(x)) # Implementacao do Python - Lerda

[0 1 2 3 4 5 6 7 8 9]
45
45


### Máximo e Mínimo
Da mesma forma, apesar de existir as funções `max()` e `min()` do Python, as implementações destas funções para o NumPy são muito mais otimizadas. 

In [17]:
print(np.max(x))
print(np.min(x))

9
0


### Agregações Multidimensionais
Pode ser interessante realizar as agregações apresentadas anteriormente ao longo de uma dimensão (linha ou coluna por exemplo). Por default, as operações de agregação passam pelo aray inteiro, basta especificar qual `axis` deve ser utilizado como direção de agregação para poder mudar este comportamento.

In [18]:
x = np.arange(16)
x = np.reshape(x,(4,4))

In [19]:
np.sum(x,axis=0) # Realiza somatorio percorrendo as linhas (verticalmente)

array([24, 28, 32, 36])

In [22]:
np.max(x,axis=1) # Encontra maior valor percorrendo colunas (horizontalmente)

array([ 3,  7, 11, 15])

### Demais Funções
| Tipo de dado | Significado |
| --- | --- |
| 'np.sum' | Computa a soma dos valores. |
| 'np.prod' | Computa o produto dos valores. |
| 'np.mean' | Computa a média dos valores. |
| 'np.std' | Computa o desvio padrão para o conjunto de valores. |
| 'np.var' | Computa a variância para o conjunto de valores. |
| 'np.min' | Encontra o menor valor dentro do conjunto de valores. |
| 'np.max' | Encontra o maior valor dentro do conjunto de valores. |
| 'np.argmin' | Encontra o indíce do menor valor. |
| 'np.argmax' | Encontra o indíce do maior valor. |
| 'np.median' | Inteiro que ocupa um byte (-128 a 127). |
| 'np.sum' | Computa a mediana para o conjunto de valores. |
| 'np.percentile' | Retorna o q-ésimo perncentil para o conjunto de valores. |
| 'np.any' | Retorna se qualquer um dos elementos é verdadeiro (OR entre elementos). |
| 'np.all' | Retorna se todos os elementos é verdadeiro (AND entre elementos). |