# NumPy: Indexação Avançanda
Neste tópico, propomos o estudo do pacote `NumPy`, cujo objetivo é fornecer suporte para arrays multidimensionais, que possuem implementações prontas para operações básicas e funções de algebra linear extremamente úteis. Este pacote é a base de grande parte dos pacotes do Python que serão futuramente estudados. A implementação deste pacote é feita através de C, logo, ele é extremamente otimizado (devido a tipagém estática e uso de memória contigua), sendo ótimo para carregar, armazenear, e manipular dados dentro de memória no Python.

## Indexação Avançada
Até então, sabemos como utilizar indexação simples (`x[0]`), indexação por fatiamento de arrays (`x[0:3]`) e utilizando mascaras booleanas (`x[x < 3]`). Outra maneira de indexar é através de "fancy indexing", que pode ser traduzida para indexação chique. Ela é semalhante a indexação normal, entretanto, ocorre a passagem de arrays de indíces, ao invés de utilizar a passagem de escalares. 

Ao passar um array de indíces, é possível acessar multiplos elementos do array ao mesmo tempo. Além disso, o shape dos indíces fornecidos é utilizado como o shape da saída, como demonstrado abaixo. 

In [28]:
import numpy as np
np.random.seed(0)
rand = np.random.RandomState(42)
x = rand.randint(100, size = 10)
print(x)
indices = np.array([[3, 5],
                    [7, 4]])
print(x[indices])

[51 92 14 71 60 20 82 86 74 74]
[[71 20]
 [86 60]]


Também é possível utilizar este tipo de indeção em arrays multidimensionais. Note que ocorre o broadcasting caso o reshape de algum dos indíces seja (1,2), e a saída é um array 2x2.  

In [29]:
y = rand.randint(100,size = 16).reshape((4,4))
print(y)
ind_lin = np.array([1,3]).reshape(2,1)
ind_col = np.array([0,2]).reshape(2,1)
print(y[ind_lin,ind_col])

[[87 99 23  2]
 [21 52  1 87]
 [29 37  1 63]
 [59 20 32 75]]
[[21]
 [32]]


## Indexação Combinada
É possível combinar as multiplas formas de indexação para obter resultados ainda mais poderosos. Abaixo combinamos um valor numérico para obter os valores da terceira linha, e então passamos uma lista para obter uma seleção de valores dessa linha reordenada. 

In [30]:
y[2,[3,0,1]]

array([63, 29, 37])

Também é possível combinarar esta técnica com fatiamento de arrays.

In [31]:
y[::2,[3,2,1]]

array([[ 2, 23, 99],
       [63,  1, 37]])

E por ultimo podemos combinar isso com o uso de mascaras booleanas.

In [32]:
mask = np.arange(4)
mask = ((mask) % (2)) != (0) 
arr = np.array([[1],[2],[3]])
y[arr, mask]

array([[52, 87],
       [37, 63],
       [20, 75]])

## Modificação de valores
Da mesma forma que podemos utilizar as diversas formas de indexação para acessar subconjuntos de arrays, podemoss utilizar eles para alterar subconjuntos destes arrays. Deve se tomar cuidado entretanto com a repetição de indíces, já que pode causar resultados inesperados. 

In [33]:
# Neste exemplo apenas a ultima alteração eh mantida
x = np.zeros(10)
i = [1,1]
values = [2,4]
x[i] = values
print(x)

[0. 4. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
# Neste exemplo, a declarao x = x + 1 eh avaliada apenas uma vez
i = [2,3,3,4,4,4]
x[i] += 1
print(x)

[0. 4. 1. 1. 1. 0. 0. 0. 0. 0.]


Para resolver problemas como o anterior, onde se deseja que a declaração seja avaliada para cada iteração, se utiliza a UFunc `at()`. O objetivo desta UFunc é realizar uma operação chamada através de uma UFunc especificando o array a ser operado, os indíces de operação, e o valor a ser utilizada para a operação. 

In [35]:
x = np.zeros(10)
np.add.at(x,i,1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


Outro método interessante a ser estudado é o `reduceat()`,  que realiza um reduce localmente para os elementos de um array ao longo de uma dimensão. 

### Aplicação: Binning de dados
A tarefa de binning consiste em agrupar dados em subgrupos que discretizam os intervalos de valores. 

In [36]:
x = np.random.randn(100) # Gera valores aleatorios entre -5 e 5
bins = np.linspace(-5,5,20) # Gera intervalos
contagem = np.zeros_like(bins) # Array de zeros do tamanho de bins
bin_elem = np.searchsorted(bins,x) # Encontra indices onde inserir bins para manter ordem
np.add.at(contagem,bin_elem,1) # Prenche array de zeros com a contagem de cada bin
print(bins)
print(contagem)

[-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684 -2.36842105
 -1.84210526 -1.31578947 -0.78947368 -0.26315789  0.26315789  0.78947368
  1.31578947  1.84210526  2.36842105  2.89473684  3.42105263  3.94736842
  4.47368421  5.        ]
[ 0.  0.  0.  0.  0.  1.  1.  7. 13. 16. 20. 19. 11.  7.  5.  0.  0.  0.
  0.  0.]
